In [1]:
import pandas as pd
import numpy as np
import requests
import geopandas as gpd

In [2]:
hd = pd.read_csv("https://data.cityofchicago.org/resource/4ijn-s7e5.csv?$limit=500000")
# you can use any of these
ward = gpd.read_file('https://data.cityofchicago.org/api/geospatial/sp34-6z76?method=export&format=GeoJSON')
police = gpd.read_file('https://data.cityofchicago.org/api/geospatial/fthy-xz3r?method=export&format=GeoJSON')

**Analyzing data**

In [ ]:
hd.head()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2593119,SKY CHOP SUEY INC,SKY CHOP SUEY INC,25159.0,Restaurant,Risk 1 (High),8616 S KEDZIE AVE,CHICAGO,IL,60652.0,2024-04-22T00:00:00.000,Complaint Re-Inspection,Fail,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",41.736414,-87.702192,"(41.7364142354004, -87.70219239358123)"
1,2593116,FLY GIRL FLY,FLY GIRL FLY,2822270.0,Catering,Risk 1 (High),125 W 46TH PL,CHICAGO,IL,60609.0,2024-04-22T00:00:00.000,Canvass Re-Inspection,Pass,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",41.810644,-87.629450,"(41.81064440590946, -87.62945032101811)"
2,2593140,ALL TOGETHER NOW,ALLTOGETHER NOW,2589262.0,Restaurant,Risk 1 (High),2119 W CHICAGO AVE,CHICAGO,IL,60622.0,2024-04-22T00:00:00.000,Canvass,Pass w/ Conditions,2. CITY OF CHICAGO FOOD SERVICE SANITATION CER...,41.895745,-87.680303,"(41.89574547491271, -87.6803034146672)"
3,2593156,MARIANO'S,MARIANO'S,2271471.0,Grocery Store,Risk 1 (High),1615 S CLARK ST,CHICAGO,IL,60616.0,2024-04-22T00:00:00.000,Complaint,Pass,36. THERMOMETERS PROVIDED & ACCURATE - Comment...,41.859630,-87.630125,"(41.85962967731282, -87.63012489927696)"
4,2593144,MERCADITO LA MONARCA,MERCADITO LA MONARCA,2956597.0,Grocery Store,Risk 1 (High),2732 W 59TH ST,CHICAGO,IL,60629.0,2024-04-22T00:00:00.000,License Re-Inspection,Pass,39. CONTAMINATION PREVENTED DURING FOOD PREPAR...,41.786536,-87.692440,"(41.78653601978693, -87.69244039932887)"

In [ ]:
hd.tail()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
271018,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,2010-01-04T00:00:00.000,Canvass,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.898431,-87.628009,"(41.89843137207629, -87.6280091630558)"
271019,67757,DUNKIN DONUTS/BASKIN-ROBBINS,DUNKIN DONUTS/BASKIN-ROBBINS,1380279.0,Restaurant,Risk 2 (Medium),100 W RANDOLPH ST,CHICAGO,IL,60601.0,2010-01-04T00:00:00.000,Tag Removal,Pass,NaN,41.884586,-87.631010,"(41.88458626715456, -87.63101044588599)"
271020,67732,WOLCOTT'S,TROQUET,1992039.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,2010-01-04T00:00:00.000,License Re-Inspection,Pass,NaN,41.961606,-87.675967,"(41.961605669949854, -87.67596676683779)"
271021,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,2010-01-04T00:00:00.000,License,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,NaN,NaN,NaN
271022,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,2010-01-04T00:00:00.000,License Re-Inspection,Pass,NaN,41.938007,-87.644755,"(41.938006880423615, -87.6447545707008)"

In [ ]:
hd.columns

Index(['inspection_id', 'dba_name', 'aka_name', 'license_', 'facility_type',
       'risk', 'address', 'city', 'state', 'zip', 'inspection_date',
       'inspection_type', 'results', 'violations', 'latitude', 'longitude',
       'location'],
      dtype='object')

In [ ]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271023 entries, 0 to 271022
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   inspection_id    271023 non-null  int64
 1   dba_name         271023 non-null  object
 2   aka_name         268551 non-null  object
 3   license_         271005 non-null  float64
 4   facility_type    265882 non-null  object
 5   risk             270940 non-null  object
 6   address          271023 non-null  object
 7   city             270862 non-null  object
 8   state            270964 non-null  object
 9   zip              270972 non-null  float64
 10  inspection_date  271023 non-null  object
 11  inspection_type  271022 non-null  object
 12  results          271023 non-null  object
 13  violations       196697 non-null  object
 14  latitude         270085 non-null  float64
 15  longitude        270085 non-null  float64
 16  location         270085 non-null  object
dtypes: float64(4), int64(1), object(12)
memory usage: 35.2+ MB

In [ ]:
hd.shape

(271023, 17)

**Analyzing how many restaurants are inspected every month/year**

method not shown in class

In [3]:
hd['inspection_date'] = pd.to_datetime(hd['inspection_date'])

In [4]:
hd['inspection_date'].dt.year

0         2024
1         2024
2         2024
3         2024
4         2024
          ...
271018    2010
271019    2010
271020    2010
271021    2010
271022    2010
Name: inspection_date, Length: 271023, dtype: int32

In [5]:
year_to_filter = 2024

In [6]:
values_for_year = hd[hd['inspection_date'].dt.year == year_to_filter]['inspection_date']

In [7]:
print(values_for_year)

0      2024-04-22
1      2024-04-22
2      2024-04-22
3      2024-04-22
4      2024-04-22
          ...
5101   2024-01-04
5102   2024-01-02
5103   2024-01-02
5104   2024-01-02
5105   2024-01-02
Name: inspection_date, Length: 5106, dtype: datetime64[ns]

Creating new columns

In [8]:
hd['inspection_date'] = pd.to_datetime(hd['inspection_date'])

In [9]:
hd['inspection_date'].value_counts()

inspection_date
2013-11-14    185
2016-09-13    149
2016-11-29    145
2014-12-16    143
2014-12-03    142
             ...
2010-08-07      1
2017-01-09      1
2010-12-18      1
2011-02-11      1
2017-02-06      1
Name: count, Length: 3611, dtype: int64

In [10]:
hd['inc_year'] = hd['inspection_date'].dt.year
hd['inc_month'] = hd['inspection_date'].dt.month
hd['inc_week'] = hd['inspection_date'].dt.weekday
hd['inc_day'] = hd['inspection_date'].dt.day

In [11]:
hd['year_month'] = hd['inc_year'].astype(str) + "-" + hd['inc_month'].astype(str) + "-01"

In [12]:
hd['count'] = 1

running groupby

In [13]:
hd.groupby('year_month')['count'].sum()

year_month
2010-1-01     1279
2010-10-01    1814
2010-11-01    1294
2010-12-01    1278
2010-2-01     1399
              ...
2023-9-01     1535
2024-1-01     1367
2024-2-01     1345
2024-3-01     1457
2024-4-01      937
Name: count, Length: 172, dtype: int64

In [ ]:
hd.groupby('year_month')['count'].sum().mean()

1575.7151162790697

In [ ]:
year_month = hd.groupby('year_month')['count'].sum()

In [ ]:
year_month.to_csv('year_month')

Inspections done per month - https://datawrapper.dwcdn.net/8o95a/1/

Inspections done per year - https://datawrapper.dwcdn.net/1UWqG/4/

**Analyzing how many restaurants are inspected by geographical area**

**Analyzing how many restaurants receive either a downgraded or upgraded inspection and Failing or Passing grade**

In [ ]:
hd.columns

Index(['inspection_id', 'dba_name', 'aka_name', 'license_', 'facility_type',
       'risk', 'address', 'city', 'state', 'zip', 'inspection_date',
       'inspection_type', 'results', 'violations', 'latitude', 'longitude',
       'location', 'inc_year', 'inc_month', 'inc_week', 'inc_day',
       'year_month', 'count'],
      dtype='object')

In [ ]:
hd.shape

(271023, 23)

In [ ]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271023 entries, 0 to 271022
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   inspection_id    271023 non-null  int64
 1   dba_name         271023 non-null  object
 2   aka_name         268551 non-null  object
 3   license_         271005 non-null  float64
 4   facility_type    265882 non-null  object
 5   risk             270940 non-null  object
 6   address          271023 non-null  object
 7   city             270862 non-null  object
 8   state            270964 non-null  object
 9   zip              270972 non-null  float64
 10  inspection_date  271023 non-null  datetime64[ns]
 11  inspection_type  271022 non-null  object
 12  results          271023 non-null  object
 13  violations       196697 non-null  object
 14  latitude         270085 non-null  float64
 15  longitude        270085 non-null  float64
 16  location         270085 non-null  object
 17  inc_year         271023 non-null  int32
 18  inc_month        271023 non-null  int32
 19  inc_week         271023 non-null  int32
 20  inc_day          271023 non-null  int32
 21  year_month       271023 non-null  object
 22  count            271023 non-null  int64
dtypes: datetime64[ns](1), float64(4), int32(4), int64(2), object(12)
memory usage: 43.4+ MB

In [ ]:
hd.head()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,violations,latitude,longitude,location,inc_year,inc_month,inc_week,inc_day,year_month,count
0,2593119,SKY CHOP SUEY INC,SKY CHOP SUEY INC,25159.0,Restaurant,Risk 1 (High),8616 S KEDZIE AVE,CHICAGO,IL,60652.0,...,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",41.736414,-87.702192,"(41.7364142354004, -87.70219239358123)",2024,4,0,22,2024-4-01,1
1,2593116,FLY GIRL FLY,FLY GIRL FLY,2822270.0,Catering,Risk 1 (High),125 W 46TH PL,CHICAGO,IL,60609.0,...,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",41.810644,-87.629450,"(41.81064440590946, -87.62945032101811)",2024,4,0,22,2024-4-01,1
2,2593140,ALL TOGETHER NOW,ALLTOGETHER NOW,2589262.0,Restaurant,Risk 1 (High),2119 W CHICAGO AVE,CHICAGO,IL,60622.0,...,2. CITY OF CHICAGO FOOD SERVICE SANITATION CER...,41.895745,-87.680303,"(41.89574547491271, -87.6803034146672)",2024,4,0,22,2024-4-01,1
3,2593156,MARIANO'S,MARIANO'S,2271471.0,Grocery Store,Risk 1 (High),1615 S CLARK ST,CHICAGO,IL,60616.0,...,36. THERMOMETERS PROVIDED & ACCURATE - Comment...,41.859630,-87.630125,"(41.85962967731282, -87.63012489927696)",2024,4,0,22,2024-4-01,1
4,2593144,MERCADITO LA MONARCA,MERCADITO LA MONARCA,2956597.0,Grocery Store,Risk 1 (High),2732 W 59TH ST,CHICAGO,IL,60629.0,...,39. CONTAMINATION PREVENTED DURING FOOD PREPAR...,41.786536,-87.692440,"(41.78653601978693, -87.69244039932887)",2024,4,0,22,2024-4-01,1

In [ ]:
hd.tail()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,violations,latitude,longitude,location,inc_year,inc_month,inc_week,inc_day,year_month,count
271018,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,...,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.898431,-87.628009,"(41.89843137207629, -87.6280091630558)",2010,1,0,4,2010-1-01,1
271019,67757,DUNKIN DONUTS/BASKIN-ROBBINS,DUNKIN DONUTS/BASKIN-ROBBINS,1380279.0,Restaurant,Risk 2 (Medium),100 W RANDOLPH ST,CHICAGO,IL,60601.0,...,NaN,41.884586,-87.631010,"(41.88458626715456, -87.63101044588599)",2010,1,0,4,2010-1-01,1
271020,67732,WOLCOTT'S,TROQUET,1992039.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,NaN,41.961606,-87.675967,"(41.961605669949854, -87.67596676683779)",2010,1,0,4,2010-1-01,1
271021,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,...,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,NaN,NaN,NaN,2010,1,0,4,2010-1-01,1
271022,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,...,NaN,41.938007,-87.644755,"(41.938006880423615, -87.6447545707008)",2010,1,0,4,2010-1-01,1

In [ ]:
inspected_restaurants = hd.groupby('dba_name').filter(lambda x: len(x) > 1)

In [ ]:
inspected_restaurants['Upgrade/Downgrade'] = np.where(inspected_restaurants['results'].shift(-1) != inspected_restaurants['results'], 'Yes', 'No')

In [ ]:
inspected_restaurants['Pass/Fail'] = np.where(inspected_restaurants['results'] == 'Pass', 'Pass', 'Fail')

In [ ]:
inspected_restaurants['Result Numerical'] = (inspected_restaurants['results'] == 'Pass').astype(int)

In [ ]:
restaurant_inspection_counts = inspected_restaurants.groupby('dba_name').size().reset_index(name='Inspection Count')

In [ ]:
inspection_scores = inspected_restaurants.groupby('dba_name')['Result Numerical'].agg(['mean', 'median']).reset_index()

In [ ]:
restaurant_data = pd.merge(restaurant_inspection_counts, inspection_scores, on='dba_name', how='left')

In [ ]:
restaurant_data['Inspection Summary'] = restaurant_data['dba_name'] + ' - Inspected ' + restaurant_data['Inspection Count'].astype(str) + ' times'

In [ ]:
print(f"Total number of inspected restaurants: {len(inspected_restaurants)}")

Total number of inspected restaurants: 265026

In [ ]:
upgrade_downgrade_counts = inspected_restaurants['Upgrade/Downgrade'].value_counts()

In [ ]:
upgrade_downgrade_counts = inspected_restaurants.groupby(['dba_name', 'Upgrade/Downgrade']).size().unstack(fill_value=0).reset_index()
upgrade_downgrade_counts = upgrade_downgrade_counts.rename(columns={'No': 'Upgraded', 'Yes': 'Downgraded'})

In [ ]:
pass_fail_counts = inspected_restaurants.groupby(['dba_name', 'Pass/Fail']).size().unstack(fill_value=0).reset_index()

In [ ]:
merged_data = restaurant_inspection_counts.merge(upgrade_downgrade_counts, on='dba_name', how='left')
merged_data = merged_data.merge(pass_fail_counts, on='dba_name', how='left')

In [ ]:
last_month = hd['inspection_date'].max().to_period('M')
hd_last_month = hd[(hd['inspection_date'].dt.to_period('M') == last_month) & (hd['facility_type'] == 'Restaurant')]

In [ ]:
restaurant_inspection_counts_last_month = hd_last_month.groupby('dba_name').size().reset_index(name='Inspection Count')

In [ ]:
hd_last_month['Upgrade/Downgrade'] = np.where(hd_last_month['results'].shift(-1) != hd_last_month['results'], 'Yes', 'No')

<ipython-input-37-e2aa56395d9a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hd_last_month['Upgrade/Downgrade'] = np.where(hd_last_month['results'].shift(-1) != hd_last_month['results'], 'Yes', 'No')

In [ ]:
hd_last_month['Pass/Fail'] = np.where(hd_last_month['results'] == 'Pass', 'Pass', 'Fail')

<ipython-input-38-b6f02a85308f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hd_last_month['Pass/Fail'] = np.where(hd_last_month['results'] == 'Pass', 'Pass', 'Fail')

In [ ]:
upgrade_downgrade_counts_last_month = hd_last_month.groupby(['dba_name', 'Upgrade/Downgrade']).size().unstack(fill_value=0).reset_index()
upgrade_downgrade_counts_last_month = upgrade_downgrade_counts_last_month.rename(columns={'No': 'Upgraded', 'Yes': 'Downgraded'})

In [ ]:
pass_fail_counts_last_month = hd_last_month.groupby(['dba_name', 'Pass/Fail']).size().unstack(fill_value=0).reset_index()

In [ ]:
merged_data_last_month = restaurant_inspection_counts_last_month.merge(upgrade_downgrade_counts_last_month, on='dba_name', how='left').merge(pass_fail_counts_last_month, on='dba_name', how='left')

In [ ]:
print(f"Total number of inspected restaurants in the last month: {len(hd_last_month)}")

Total number of inspected restaurants in the last month: 652

In [ ]:
for month in hd['inspection_date'].dt.to_period('M').sort_values().unique():
  hd_month = hd[(hd['inspection_date'].dt.to_period('M') == month) & (hd['facility_type'] == 'Restaurant')]

In [ ]:
merged_data_last_month.to_csv('restaurant_inspection_summary_last_month.csv')

**List of restaurants who are failing their inspections**

areas with common fail inspections

In [ ]:
#create a geodataframe from build
hd_geo = gpd.GeoDataFrame(
hd, geometry= gpd.points_from_xy(hd['longitude'], hd['latitude']), crs="EPSG:4326"
)

In [ ]:
#join ward
hd_geo_w = hd_geo.sjoin(ward, how="left", predicate='within' )

In [ ]:
#drop index
hd_geo_w= hd_geo_w.drop(columns=['index_right'], axis=1)

In [ ]:
#join police
hd_geo_w_p = hd_geo_w.sjoin(police, how="left", predicate='within')

In [ ]:
hd_geo_w_p.head()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
0,2593119,SKY CHOP SUEY INC,SKY CHOP SUEY INC,25159.0,Restaurant,Risk 1 (High),8616 S KEDZIE AVE,CHICAGO,IL,60652.0,...,22,2024-4-01,1,POINT (-87.70219 41.73641),183256966.765,65699.143324,18,12.0,8TH,8
1,2593116,FLY GIRL FLY,FLY GIRL FLY,2822270.0,Catering,Risk 1 (High),125 W 46TH PL,CHICAGO,IL,60609.0,...,22,2024-4-01,1,POINT (-87.62945 41.81064),123341548.953,81530.2751668,3,23.0,2ND,2
2,2593140,ALL TOGETHER NOW,ALLTOGETHER NOW,2589262.0,Restaurant,Risk 1 (High),2119 W CHICAGO AVE,CHICAGO,IL,60622.0,...,22,2024-4-01,1,POINT (-87.68030 41.89575),69757593.8542,102569.70148,1,14.0,12TH,12
3,2593156,MARIANO'S,MARIANO'S,2271471.0,Grocery Store,Risk 1 (High),1615 S CLARK ST,CHICAGO,IL,60616.0,...,22,2024-4-01,1,POINT (-87.63012 41.85963),123341548.953,81530.2751668,3,21.0,1ST,1
4,2593144,MERCADITO LA MONARCA,MERCADITO LA MONARCA,2956597.0,Grocery Store,Risk 1 (High),2732 W 59TH ST,CHICAGO,IL,60629.0,...,22,2024-4-01,1,POINT (-87.69244 41.78654),103143638.546,97901.3238332,16,12.0,8TH,8

In [ ]:
hd_geo_w_p.tail(20)

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
271003,164252,SUPER DOG'S SUBMARINES INC,SUPER DOG'S SUBMARINES INC,2008759.0,Restaurant,Risk 2 (Medium),1442 W 103RD ST,CHICAGO,IL,60643.0,...,5,2010-1-01,1,POINT (-87.65895 41.70685),214115105.843,102339.878771,19,8.0,22ND,22
271004,124257,"LIDO, INC.",LIDO BANQUETS,17145.0,Restaurant,Risk 1 (High),5504 N MILWAUKEE AVE,CHICAGO,IL,60630.0,...,5,2010-1-01,1,POINT (-87.77347 41.98175),125334245.511,76714.8413866,45,11.0,16TH,16
271005,80208,Dunkin Donuts,Dunkin Donuts,2013340.0,Restaurant,Risk 1 (High),2800 W Lawrence AVE BLDG,CHICAGO,IL,60625.0,...,5,2010-1-01,1,POINT (-87.69872 41.96864),95929056.6812,48374.9136177,40,1.0,20TH,20
271006,134239,BORNIQUEN RESTAURANT,BORNIQUEN RESTAURANT,32942.0,Restaurant,Risk 1 (High),1720 N CALIFORNIA AVE,CHICAGO,IL,60647.0,...,5,2010-1-01,1,POINT (-87.69720 41.91269),69757593.8542,102569.70148,1,6.0,14TH,14
271007,124256,FERNANDO'S MEXICAN GRILL & PIZZA,FERNANDO'S MEXICAN GRILL & PIZZA,1915768.0,Restaurant,Risk 1 (High),7148 N HARLEM AVE,CHICAGO,IL,60631.0,...,5,2010-1-01,1,POINT (-87.80679 42.01136),484238238.97,252516.011482,41,11.0,16TH,16
271008,70273,THE GREAT AMERICAN BAGEL,THE GREAT AMERICAN BAGEL (T3-H10),1879164.0,Restaurant,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,...,5,2010-1-01,1,POINT (-87.90687 42.00875),484238238.97,252516.011482,41,11.0,16TH,16
271009,67848,SAFAH FOOD & LIQUOR INC,SAFAH FOOD & LIQUOR INC,14103.0,Grocery Store,Risk 3 (Low),7105 S RACINE AVE,CHICAGO,IL,60636.0,...,5,2010-1-01,1,POINT (-87.65396 41.76490),120539114.428,69925.2023858,6,16.0,7TH,7
271010,67739,EL TACONAZO RESTAURANT,EL TACONAZO RESTAURANT,1964480.0,Restaurant,Risk 1 (High),5849 S KEDZIE AVE,CHICAGO,IL,60629.0,...,5,2010-1-01,1,POINT (-87.70321 41.78662),143011018.899,90165.7974072,14,12.0,8TH,8
271011,70272,THE DOGHOUSE,THE DOGHOUSE,1681450.0,NaN,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,...,5,2010-1-01,1,POINT (-87.90687 42.00875),484238238.97,252516.011482,41,11.0,16TH,16
271012,68250,Tots Express Learning Center,NaN,2002536.0,Daycare (2 - 6 Years),Risk 1 (High),1705-07 E 87th ST FL,CHICAGO,IL,60617.0,...,5,2010-1-01,1,POINT (-87.58249 41.73685),162845783.237,89830.3932001,8,18.0,4TH,4
271013,134238,FUNSTON ANNEX ELEM. SCHOOL,FUNSTON (ANNEX) ELEM. SCHOOL,1964634.0,School,Risk 1 (High),3616 W ARMITAGE AVE,CHICAGO,IL,60647.0,...,5,2010-1-01,1,POINT (-87.71746 41.91738),70391187.5645,69089.8822547,26,5.0,25TH,25
271014,118296,FAIRPLAY FINER FOOD,FAIRPLAY FINER FOOD,10940.0,Grocery Store,Risk 1 (High),2200 S WESTERN AVE,CHICAGO,IL,60608.0,...,5,2010-1-01,1,POINT (-87.68579 41.85198),142879662.243,119977.208819,28,20.0,10TH,10
271015,98313,WHIPPLE STORE,WHIPPLE STORE,2009114.0,Grocery Store,Risk 3 (Low),4301 N WHIPPLE ST,CHICAGO,IL,60618.0,...,5,2010-1-01,1,POINT (-87.70438 41.95949),70214893.3538,47062.4200753,33,0.0,17TH,17
271016,67733,WOLCOTT'S,TROQUET,1992040.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,4,2010-1-01,1,POINT (-87.67597 41.96161),87363636.3844,53371.3055095,47,4.0,19TH,19
271017,70269,mr.daniel's,mr.daniel's,1899292.0,Restaurant,Risk 1 (High),5645 W BELMONT AVE,CHICAGO,IL,60634.0,...,4,2010-1-01,1,POINT (-87.76832 41.93844),69739758.4303,50635.7831536,31,5.0,25TH,25
271018,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,...,4,2010-1-01,1,POINT (-87.62801 41.89843),53934808.8716,110739.852187,2,13.0,18TH,18
271019,67757,DUNKIN DONUTS/BASKIN-ROBBINS,DUNKIN DONUTS/BASKIN-ROBBINS,1380279.0,Restaurant,Risk 2 (Medium),100 W RANDOLPH ST,CHICAGO,IL,60601.0,...,4,2010-1-01,1,POINT (-87.63101 41.88459),71494714.6921,62491.4598917,42,21.0,1ST,1
271020,67732,WOLCOTT'S,TROQUET,1992039.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,4,2010-1-01,1,POINT (-87.67597 41.96161),87363636.3844,53371.3055095,47,4.0,19TH,19
271021,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,...,4,2010-1-01,1,POINT EMPTY,NaN,NaN,NaN,NaN,NaN,NaN
271022,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,...,4,2010-1-01,1,POINT (-87.64475 41.93801),49422863.0048,46466.2721725,44,4.0,19TH,19

**Most fails from restaurants in city and zip**

In [ ]:
#create a geodataframe from build
hd_geo = gpd.GeoDataFrame(
hd, geometry= gpd.points_from_xy(hd['longitude'], hd['latitude']), crs="EPSG:4326"
)

In [ ]:
#join ward
hd_geo_w = hd_geo.sjoin(ward, how="left", predicate='within' )

In [ ]:
#drop index
hd_geo_w= hd_geo_w.drop(columns=['index_right'], axis=1)

In [ ]:
#join police
hd_geo_w_p = hd_geo_w.sjoin(police, how="left", predicate='within')

**Tidy Data Principles**

In [ ]:
hd_geo_w_p.head()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
0,2593119,SKY CHOP SUEY INC,SKY CHOP SUEY INC,25159.0,Restaurant,Risk 1 (High),8616 S KEDZIE AVE,CHICAGO,IL,60652.0,...,22,2024-4-01,1,POINT (-87.70219 41.73641),183256966.765,65699.143324,18,12.0,8TH,8
1,2593116,FLY GIRL FLY,FLY GIRL FLY,2822270.0,Catering,Risk 1 (High),125 W 46TH PL,CHICAGO,IL,60609.0,...,22,2024-4-01,1,POINT (-87.62945 41.81064),123341548.953,81530.2751668,3,23.0,2ND,2
2,2593140,ALL TOGETHER NOW,ALLTOGETHER NOW,2589262.0,Restaurant,Risk 1 (High),2119 W CHICAGO AVE,CHICAGO,IL,60622.0,...,22,2024-4-01,1,POINT (-87.68030 41.89575),69757593.8542,102569.70148,1,14.0,12TH,12
3,2593156,MARIANO'S,MARIANO'S,2271471.0,Grocery Store,Risk 1 (High),1615 S CLARK ST,CHICAGO,IL,60616.0,...,22,2024-4-01,1,POINT (-87.63012 41.85963),123341548.953,81530.2751668,3,21.0,1ST,1
4,2593144,MERCADITO LA MONARCA,MERCADITO LA MONARCA,2956597.0,Grocery Store,Risk 1 (High),2732 W 59TH ST,CHICAGO,IL,60629.0,...,22,2024-4-01,1,POINT (-87.69244 41.78654),103143638.546,97901.3238332,16,12.0,8TH,8

In [ ]:
hd_geo_w_p.tail(20)

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
271003,164252,SUPER DOG'S SUBMARINES INC,SUPER DOG'S SUBMARINES INC,2008759.0,Restaurant,Risk 2 (Medium),1442 W 103RD ST,CHICAGO,IL,60643.0,...,5,2010-1-01,1,POINT (-87.65895 41.70685),214115105.843,102339.878771,19,8.0,22ND,22
271004,124257,"LIDO, INC.",LIDO BANQUETS,17145.0,Restaurant,Risk 1 (High),5504 N MILWAUKEE AVE,CHICAGO,IL,60630.0,...,5,2010-1-01,1,POINT (-87.77347 41.98175),125334245.511,76714.8413866,45,11.0,16TH,16
271005,80208,Dunkin Donuts,Dunkin Donuts,2013340.0,Restaurant,Risk 1 (High),2800 W Lawrence AVE BLDG,CHICAGO,IL,60625.0,...,5,2010-1-01,1,POINT (-87.69872 41.96864),95929056.6812,48374.9136177,40,1.0,20TH,20
271006,134239,BORNIQUEN RESTAURANT,BORNIQUEN RESTAURANT,32942.0,Restaurant,Risk 1 (High),1720 N CALIFORNIA AVE,CHICAGO,IL,60647.0,...,5,2010-1-01,1,POINT (-87.69720 41.91269),69757593.8542,102569.70148,1,6.0,14TH,14
271007,124256,FERNANDO'S MEXICAN GRILL & PIZZA,FERNANDO'S MEXICAN GRILL & PIZZA,1915768.0,Restaurant,Risk 1 (High),7148 N HARLEM AVE,CHICAGO,IL,60631.0,...,5,2010-1-01,1,POINT (-87.80679 42.01136),484238238.97,252516.011482,41,11.0,16TH,16
271008,70273,THE GREAT AMERICAN BAGEL,THE GREAT AMERICAN BAGEL (T3-H10),1879164.0,Restaurant,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,...,5,2010-1-01,1,POINT (-87.90687 42.00875),484238238.97,252516.011482,41,11.0,16TH,16
271009,67848,SAFAH FOOD & LIQUOR INC,SAFAH FOOD & LIQUOR INC,14103.0,Grocery Store,Risk 3 (Low),7105 S RACINE AVE,CHICAGO,IL,60636.0,...,5,2010-1-01,1,POINT (-87.65396 41.76490),120539114.428,69925.2023858,6,16.0,7TH,7
271010,67739,EL TACONAZO RESTAURANT,EL TACONAZO RESTAURANT,1964480.0,Restaurant,Risk 1 (High),5849 S KEDZIE AVE,CHICAGO,IL,60629.0,...,5,2010-1-01,1,POINT (-87.70321 41.78662),143011018.899,90165.7974072,14,12.0,8TH,8
271011,70272,THE DOGHOUSE,THE DOGHOUSE,1681450.0,NaN,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,...,5,2010-1-01,1,POINT (-87.90687 42.00875),484238238.97,252516.011482,41,11.0,16TH,16
271012,68250,Tots Express Learning Center,NaN,2002536.0,Daycare (2 - 6 Years),Risk 1 (High),1705-07 E 87th ST FL,CHICAGO,IL,60617.0,...,5,2010-1-01,1,POINT (-87.58249 41.73685),162845783.237,89830.3932001,8,18.0,4TH,4
271013,134238,FUNSTON ANNEX ELEM. SCHOOL,FUNSTON (ANNEX) ELEM. SCHOOL,1964634.0,School,Risk 1 (High),3616 W ARMITAGE AVE,CHICAGO,IL,60647.0,...,5,2010-1-01,1,POINT (-87.71746 41.91738),70391187.5645,69089.8822547,26,5.0,25TH,25
271014,118296,FAIRPLAY FINER FOOD,FAIRPLAY FINER FOOD,10940.0,Grocery Store,Risk 1 (High),2200 S WESTERN AVE,CHICAGO,IL,60608.0,...,5,2010-1-01,1,POINT (-87.68579 41.85198),142879662.243,119977.208819,28,20.0,10TH,10
271015,98313,WHIPPLE STORE,WHIPPLE STORE,2009114.0,Grocery Store,Risk 3 (Low),4301 N WHIPPLE ST,CHICAGO,IL,60618.0,...,5,2010-1-01,1,POINT (-87.70438 41.95949),70214893.3538,47062.4200753,33,0.0,17TH,17
271016,67733,WOLCOTT'S,TROQUET,1992040.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,4,2010-1-01,1,POINT (-87.67597 41.96161),87363636.3844,53371.3055095,47,4.0,19TH,19
271017,70269,mr.daniel's,mr.daniel's,1899292.0,Restaurant,Risk 1 (High),5645 W BELMONT AVE,CHICAGO,IL,60634.0,...,4,2010-1-01,1,POINT (-87.76832 41.93844),69739758.4303,50635.7831536,31,5.0,25TH,25
271018,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,...,4,2010-1-01,1,POINT (-87.62801 41.89843),53934808.8716,110739.852187,2,13.0,18TH,18
271019,67757,DUNKIN DONUTS/BASKIN-ROBBINS,DUNKIN DONUTS/BASKIN-ROBBINS,1380279.0,Restaurant,Risk 2 (Medium),100 W RANDOLPH ST,CHICAGO,IL,60601.0,...,4,2010-1-01,1,POINT (-87.63101 41.88459),71494714.6921,62491.4598917,42,21.0,1ST,1
271020,67732,WOLCOTT'S,TROQUET,1992039.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,4,2010-1-01,1,POINT (-87.67597 41.96161),87363636.3844,53371.3055095,47,4.0,19TH,19
271021,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,...,4,2010-1-01,1,POINT EMPTY,NaN,NaN,NaN,NaN,NaN,NaN
271022,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,...,4,2010-1-01,1,POINT (-87.64475 41.93801),49422863.0048,46466.2721725,44,4.0,19TH,19

In [ ]:
hd_geo_w_p.columns

Index(['inspection_id', 'dba_name', 'aka_name', 'license_', 'facility_type',
       'risk', 'address', 'city', 'state', 'zip', 'inspection_date',
       'inspection_type', 'results', 'violations', 'latitude', 'longitude',
       'location', 'inc_year', 'inc_month', 'inc_week', 'inc_day',
       'year_month', 'count', 'geometry', 'shape_area', 'shape_leng', 'ward',
       'index_right', 'dist_label', 'dist_num'],
      dtype='object')

In [ ]:
hd_geo_w_p.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 271023 entries, 0 to 271022
Data columns (total 30 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   inspection_id    271023 non-null  int64
 1   dba_name         271023 non-null  object
 2   aka_name         268551 non-null  object
 3   license_         271005 non-null  float64
 4   facility_type    265882 non-null  object
 5   risk             270940 non-null  object
 6   address          271023 non-null  object
 7   city             270862 non-null  object
 8   state            270964 non-null  object
 9   zip              270972 non-null  float64
 10  inspection_date  271023 non-null  datetime64[ns]
 11  inspection_type  271022 non-null  object
 12  results          271023 non-null  object
 13  violations       196697 non-null  object
 14  latitude         270085 non-null  float64
 15  longitude        270085 non-null  float64
 16  location         270085 non-null  object
 17  inc_year         271023 non-null  int32
 18  inc_month        271023 non-null  int32
 19  inc_week         271023 non-null  int32
 20  inc_day          271023 non-null  int32
 21  year_month       271023 non-null  object
 22  count            271023 non-null  int64
 23  geometry         271023 non-null  geometry
 24  shape_area       269796 non-null  object
 25  shape_leng       269796 non-null  object
 26  ward             269796 non-null  object
 27  index_right      269796 non-null  float64
 28  dist_label       269796 non-null  object
 29  dist_num         269796 non-null  object
dtypes: datetime64[ns](1), float64(5), geometry(1), int32(4), int64(2), object(17)
memory usage: 60.0+ MB

In [ ]:
hd_geo_w_p.shape

(271023, 30)

Filter, conditional logic and a loop
(sorted data by zip and city)

In [ ]:
hd_geo_w_p[(hd_geo_w_p['facility_type'] == "Restaurant")]

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
0,2593119,SKY CHOP SUEY INC,SKY CHOP SUEY INC,25159.0,Restaurant,Risk 1 (High),8616 S KEDZIE AVE,CHICAGO,IL,60652.0,...,22,2024-4-01,1,POINT (-87.70219 41.73641),183256966.765,65699.143324,18,12.0,8TH,8
2,2593140,ALL TOGETHER NOW,ALLTOGETHER NOW,2589262.0,Restaurant,Risk 1 (High),2119 W CHICAGO AVE,CHICAGO,IL,60622.0,...,22,2024-4-01,1,POINT (-87.68030 41.89575),69757593.8542,102569.70148,1,14.0,12TH,12
6,2593108,TUMANS,TUMAN'S,1273473.0,Restaurant,Risk 1 (High),2159 W CHICAGO AVE,CHICAGO,IL,60622.0,...,19,2024-4-01,1,POINT (-87.68182 41.89572),69757593.8542,102569.70148,1,14.0,12TH,12
7,2593081,THE QUEEN MARY,THE QUEEN MARY,2437419.0,Restaurant,Risk 1 (High),2125 W DIVISION ST,CHICAGO,IL,60622.0,...,19,2024-4-01,1,POINT (-87.68073 41.90302),53934808.8716,110739.852187,2,14.0,12TH,12
9,2593067,KASAMA,KASAMA,2709474.0,Restaurant,Risk 1 (High),1001 N WINCHESTER AVE,CHICAGO,IL,60622.0,...,19,2024-4-01,1,POINT (-87.67579 41.89966),53934808.8716,110739.852187,2,14.0,12TH,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271018,104236,TEMPO CAFE,TEMPO CAFE,80916.0,Restaurant,Risk 1 (High),6 E CHESTNUT ST,CHICAGO,IL,60611.0,...,4,2010-1-01,1,POINT (-87.62801 41.89843),53934808.8716,110739.852187,2,13.0,18TH,18
271019,67757,DUNKIN DONUTS/BASKIN-ROBBINS,DUNKIN DONUTS/BASKIN-ROBBINS,1380279.0,Restaurant,Risk 2 (Medium),100 W RANDOLPH ST,CHICAGO,IL,60601.0,...,4,2010-1-01,1,POINT (-87.63101 41.88459),71494714.6921,62491.4598917,42,21.0,1ST,1
271020,67732,WOLCOTT'S,TROQUET,1992039.0,Restaurant,Risk 1 (High),1834 W MONTROSE AVE,CHICAGO,IL,60613.0,...,4,2010-1-01,1,POINT (-87.67597 41.96161),87363636.3844,53371.3055095,47,4.0,19TH,19
271021,67738,MICHAEL'S ON MAIN CAFE,MICHAEL'S ON MAIN CAFE,2008948.0,Restaurant,Risk 1 (High),8750 W BRYN WAWR AVE,CHICAGO,IL,60631.0,...,4,2010-1-01,1,POINT EMPTY,NaN,NaN,NaN,NaN,NaN,NaN
271022,52234,Cafe 608,Cafe 608,2013328.0,Restaurant,Risk 1 (High),608 W BARRY AVE,CHICAGO,IL,60657.0,...,4,2010-1-01,1,POINT (-87.64475 41.93801),49422863.0048,46466.2721725,44,4.0,19TH,19

In [ ]:
hd_geo_w_p_sort = hd_geo_w_p.sort_values(by=['city'], ascending=True)

In [ ]:
hd_geo_w_p_sort.head(5)

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
119693,2059706,MOJO SOUTH WACKER,MOJO SOUTH WACKER,2534918.0,Restaurant,Risk 1 (High),200 S WACKER DR,312CHICAGO,IL,60606.0,...,6,2017-6-01,1,POINT (-87.63710 41.87928),71494714.6921,62491.4598917,42,21.0,1ST,1
60386,2386974,MOJO SOUTH WACKER,MOJO SOUTH WACKER,2534918.0,Restaurant,Risk 1 (High),200 S WACKER DR,312CHICAGO,IL,60606.0,...,9,2020-9-01,1,POINT (-87.63710 41.87928),71494714.6921,62491.4598917,42,21.0,1ST,1
120393,2050982,MOJO SOUTH WACKER,MOJO SOUTH WACKER,2534918.0,Restaurant,Risk 1 (High),200 S WACKER DR,312CHICAGO,IL,60606.0,...,24,2017-5-01,1,POINT (-87.63710 41.87928),71494714.6921,62491.4598917,42,21.0,1ST,1
5461,2587155,MOJO SOUTH WACKER,MOJO SOUTH WACKER,2534918.0,Restaurant,Risk 1 (High),200 S WACKER DR,312CHICAGO,IL,60606.0,...,19,2023-12-01,1,POINT (-87.63710 41.87928),71494714.6921,62491.4598917,42,21.0,1ST,1
81580,2293744,NOURISH,NOURISH,2653129.0,Shared Kitchen User (Short Term),Risk 2 (Medium),1307 CARDINAL DR,ALGONQUIN,IL,60102.0,...,18,2019-6-01,1,POINT EMPTY,NaN,NaN,NaN,NaN,NaN,NaN

Tidy Principles - What do they do and What do they mean?


*   Melt data: transforms wide data into long data(for multiple columns)

*   Pivot data: pivot long data (often one column) into wide data(multiple columns)

*   Joins data: this is used when we want two pieces of data joined together. This method also includes and follows through with using inner and left. Inner means together and left/right means on either side of that specific column.

In [ ]:
hd_geo_w_p.head()

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,...,inc_day,year_month,count,geometry,shape_area,shape_leng,ward,index_right,dist_label,dist_num
0,2593119,SKY CHOP SUEY INC,SKY CHOP SUEY INC,25159.0,Restaurant,Risk 1 (High),8616 S KEDZIE AVE,CHICAGO,IL,60652.0,...,22,2024-4-01,1,POINT (-87.70219 41.73641),183256966.765,65699.143324,18,12.0,8TH,8
1,2593116,FLY GIRL FLY,FLY GIRL FLY,2822270.0,Catering,Risk 1 (High),125 W 46TH PL,CHICAGO,IL,60609.0,...,22,2024-4-01,1,POINT (-87.62945 41.81064),123341548.953,81530.2751668,3,23.0,2ND,2
2,2593140,ALL TOGETHER NOW,ALLTOGETHER NOW,2589262.0,Restaurant,Risk 1 (High),2119 W CHICAGO AVE,CHICAGO,IL,60622.0,...,22,2024-4-01,1,POINT (-87.68030 41.89575),69757593.8542,102569.70148,1,14.0,12TH,12
3,2593156,MARIANO'S,MARIANO'S,2271471.0,Grocery Store,Risk 1 (High),1615 S CLARK ST,CHICAGO,IL,60616.0,...,22,2024-4-01,1,POINT (-87.63012 41.85963),123341548.953,81530.2751668,3,21.0,1ST,1
4,2593144,MERCADITO LA MONARCA,MERCADITO LA MONARCA,2956597.0,Grocery Store,Risk 1 (High),2732 W 59TH ST,CHICAGO,IL,60629.0,...,22,2024-4-01,1,POINT (-87.69244 41.78654),103143638.546,97901.3238332,16,12.0,8TH,8

In [ ]:
hd_df_melt = pd.melt( hd_geo_w_p_sort, id_vars=['city','zip','facility_type'], value_vars=['results'] )

In [ ]:
hd_df_melt.head(20)

,city,zip,facility_type,variable,value
0,312CHICAGO,60606.0,Restaurant,results,Pass
1,312CHICAGO,60606.0,Restaurant,results,Pass w/ Conditions
2,312CHICAGO,60606.0,Restaurant,results,Not Ready
3,312CHICAGO,60606.0,Restaurant,results,Pass
4,ALGONQUIN,60102.0,Shared Kitchen User (Short Term),results,Pass w/ Conditions
5,ALSIP,60803.0,Mobile Food Dispenser,results,Pass
6,ALSIP,60803.0,Mobile Food Dispenser,results,Fail
7,ALSIP,60803.0,Mobile Food Dispenser,results,Pass
8,BANNOCKBURNDEERFIELD,60015.0,PUSHCART,results,Pass w/ Conditions
9,BANNOCKBURNDEERFIELD,60015.0,PUSHCART,results,Pass w/ Conditions
10,BERWYN,60402.0,Mobile Food Preparer,results,Pass w/ Conditions
11,BERWYN,60402.0,Mobile Food Dispenser,results,Fail
12,BERWYN,60402.0,Mobile Food Dispenser,results,Pass
13,BERWYN,60402.0,Shared Kitchen User (Long Term),results,Out of Business
14,BERWYN,60402.0,Shared Kitchen User (Long Term),results,Pass
15,BERWYN,60402.0,NaN,results,Pass
16,BLOOMINGDALE,60108.0,Mobile Food Dispenser,results,Pass
17,BLUE ISLAND,60406.0,Shared Kitchen User (Long Term),results,Pass
18,BLUE ISLAND,60406.0,Shared Kitchen User (Long Term),results,Pass
19,BOLINGBROOK,60440.0,Shared Kitchen User (Long Term),results,Pass

In [ ]:
hd_df_melt.sort_values(['facility_type','variable' ]).head(14)

           city      zip        facility_type variable            value
96433   CHICAGO  60604.0  (convenience store)  results             Pass
100623  CHICAGO  60649.0        (gas station)  results             Pass
100720  CHICAGO  60649.0        (gas station)  results             Fail
30405   CHICAGO  60659.0    1005 NURSING HOME  results  Out of Business
67739   CHICAGO  60659.0    1005 NURSING HOME  results             Pass
69304   CHICAGO  60659.0    1005 NURSING HOME  results             Fail
8565    CHICAGO  60639.0                 1023  results             Fail
8731    CHICAGO  60639.0                 1023  results             Pass
8757    CHICAGO  60639.0                 1023  results             Pass
48544   CHICAGO  60639.0                 1023  results  Out of Business
48622   CHICAGO  60639.0                 1023  results  Out of Business
95979   CHICAGO  60639.0                 1023  results             Pass
95982   CHICAGO  60639.0                 1023  results             Pass
96002   CHICAGO  60639.0                 1023  results             Pass

In [ ]:
hd_melt_sort = hd_df_melt.sort_values(by=['city'], ascending=True).reset_index()

In [ ]:
hd_melt_sort.head(20)

,index,city,zip,facility_type,variable,value
0,0,312CHICAGO,60606.0,Restaurant,results,Pass
1,1,312CHICAGO,60606.0,Restaurant,results,Pass w/ Conditions
2,2,312CHICAGO,60606.0,Restaurant,results,Not Ready
3,3,312CHICAGO,60606.0,Restaurant,results,Pass
4,4,ALGONQUIN,60102.0,Shared Kitchen User (Short Term),results,Pass w/ Conditions
5,5,ALSIP,60803.0,Mobile Food Dispenser,results,Pass
6,6,ALSIP,60803.0,Mobile Food Dispenser,results,Fail
7,7,ALSIP,60803.0,Mobile Food Dispenser,results,Pass
8,8,BANNOCKBURNDEERFIELD,60015.0,PUSHCART,results,Pass w/ Conditions
9,9,BANNOCKBURNDEERFIELD,60015.0,PUSHCART,results,Pass w/ Conditions
10,14,BERWYN,60402.0,Shared Kitchen User (Long Term),results,Pass
11,13,BERWYN,60402.0,Shared Kitchen User (Long Term),results,Out of Business
12,15,BERWYN,60402.0,NaN,results,Pass
13,11,BERWYN,60402.0,Mobile Food Dispenser,results,Fail
14,10,BERWYN,60402.0,Mobile Food Preparer,results,Pass w/ Conditions
15,12,BERWYN,60402.0,Mobile Food Dispenser,results,Pass
16,16,BLOOMINGDALE,60108.0,Mobile Food Dispenser,results,Pass
17,17,BLUE ISLAND,60406.0,Shared Kitchen User (Long Term),results,Pass
18,18,BLUE ISLAND,60406.0,Shared Kitchen User (Long Term),results,Pass
19,19,BOLINGBROOK,60440.0,Shared Kitchen User (Long Term),results,Pass

In [ ]:
hd_geo_w_p['results'].value_counts()

results
Pass                    139494
Fail                     53006
Pass w/ Conditions       41266
Out of Business          22829
No Entry                 10879
Not Ready                 3463
Business Not Located        86
Name: count, dtype: int64

In [ ]:
hd_geo_w_p['failed_results']=np.where(hd_geo_w_p['results'].isin(['Fail','Out of Business']),1,0)

In [ ]:
hd_geo_w_p['failed_results'].value_counts()

failed_results
0    195188
1     75835
Name: count, dtype: int64

In [ ]:
hd_geo_w_p.groupby(['city','zip'])['failed_results'].sum().reset_index()

                     city      zip  failed_results
0              312CHICAGO  60606.0               0
1               ALGONQUIN  60102.0               0
2                   ALSIP  60803.0               1
3    BANNOCKBURNDEERFIELD  60015.0               0
4                  BERWYN  60402.0               2
..                    ...      ...             ...
173               chicago  60629.0              22
174               chicago  60638.0               1
175               chicago  60647.0               5
176               chicago  60649.0               9
177   chicagoBEDFORD PARK  60629.0               1

[178 rows x 3 columns]

In [ ]:
hd_geo_w_p.groupby(['city','zip'])['failed_results'].size().reset_index()

                     city      zip  failed_results
0              312CHICAGO  60606.0               4
1               ALGONQUIN  60102.0               1
2                   ALSIP  60803.0               3
3    BANNOCKBURNDEERFIELD  60015.0               2
4                  BERWYN  60402.0               6
..                    ...      ...             ...
173               chicago  60629.0              88
174               chicago  60638.0               1
175               chicago  60647.0               9
176               chicago  60649.0              38
177   chicagoBEDFORD PARK  60629.0               1

[178 rows x 3 columns]

Loop

In [ ]:
inspection_options = ["pass", "fail", "downgraded", "upgraded"]

In [ ]:
for element in inspection_options:

  print("inspection"+ "=" + element)

inspection=pass
inspection=fail
inspection=downgraded
inspection=upgraded